version: '2'
services:
  db:
    image: postgres:9.5
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: q-hiring-abstaction
      POSTGRES_USER: postgres
  app:
    build: .
    command: npm start
    volumes:
      - ".:/Q-hiring-abstraction/"
    ports:
      - "3001:3001"
    links:
      - db
    environment:
      DB_USER: postgres
      DB_NAME: q-hiring-abstaction
      DB_PASSWORD: password
      DB_HOST: db
